### ISSUE TITLE
fix black rectangle around workspaces thumbnail when using blur my shell with yadwaita-dark shell theme

### ISSUE THREAD

**Issue by teh404guy** [tofutech/yadwaita-shell#2]
steps to reproduce: 
1. install yadwaita-dark them
2. enable it in gnome tweaks
3. install blur my shell
4. everything looks fine and homogeneous except for the black bar around the workspaces
screenshot: 
![Capture d’écran du 2021-05-30 11-44-04](https://user-images.githubusercontent.com/62482190/120101491-3f5b1900-c13e-11eb-9d4a-9bb88e317d03.png)

**Comment by teh404guy** [comment]
also it looks fine with normal yadwaita but i don't like the color pallet with blur my shell and my background

**Comment by tofutech** [comment]
I have three different systems here to test on and cannot replicate this on any of them.

**Comment by tofutech** [comment]
I would check any other extensions that may be causing issue. As you can see here, Blur My Shell works fine with the theme on my system (and this is exactly how it looks on all of my test machines.) If you send me your extension list I can take a look at what might be causing the issue but in the end it would be up to the extension developer for the most part if that is the case..
![Screenshot from 2021-05-30 09-51-55](https://user-images.githubusercontent.com/81934761/120110024-facd7e80-c139-11eb-871b-3b2c8715622d.png)

**Comment by teh404guy** [comment]
i just realized this might be an issue with gnome 40 improvements extension and not necessarily blur my shell
since i forgot that it replace the search bar in the overview with desktop thumbnails
